// GENERATED by tools/build_site.py from the two policy Markdown files.
// Edit PRIVACY_POLICY.md / PRIVACY_POLICY_EN.md and run the generator.
abstract final class PrivacyPolicyText {
  static const String toEnglishLabel = 'English';
  static const String toHebrewLabel = 'עברית';
  static const String hebrewTitle = 'מדיניות פרטיות';
  static const String englishTitle = 'Privacy Policy';

  static const String hebrew = '''
מדיניות פרטיות — שדכן

עודכן לאחרונה: 25 בספטמבר 2026

מדיניות זו חלה על אפליקציית שדכן ועל אתר המידע שלה. האפליקציה פותחה ומופעלת בידי גלעד שטרוזמן ("אנחנו"), והוא בעל השליטה במידע המתואר כאן. לשאלות ולבקשות פרטיות: giladsh22@gmail.com.

בקצרה

האפליקציה היא local-first: המאגר הפעיל נמצא במכשיר וממשיך לעבוד גם ללא אינטרנט. עם זאת, חשבון משתמש הוא חובה, וגיבוי מוצפן בתעבורה נשמר אוטומטית ב-Firebase תחת מזהה החשבון. אין באפליקציה פרסומות, SDK של אנליטיקה, SDK לדיווח קריסות, עוגיות או מעקב התנהגותי, ואיננו מוכרים מידע אישי.

1. המידע שהאפליקציה מעבדת

החשבון שלכם

אפשר להיכנס באמצעות Google, באמצעות Apple במכשירי Apple נתמכים, או באמצעות כתובת דוא"ל וסיסמה. Firebase Authentication מעבד את מזהה החשבון, ספק ההתחברות, כתובת הדוא"ל ופרטי פרופיל בסיסיים שספק ההתחברות מוסר. סיסמאות של חשבונות דוא"ל מטופלות בידי Firebase ואינן גלויות לנו. לצורכי אבטחה ומניעת שימוש לרעה Firebase עשוי לעבד גם כתובת IP, user-agent ויומני התחברות. לפני הכניסה או לאחר יציאה עשוי להיווצר מזהה Firebase אנונימי טכני וזמני; הוא אינו מקבל גיבוי ואינו מאפשר לעבור את מסך הכניסה.

מאגר השידוכים

אתם עשויים להזין מידע על עצמכם ועל אנשים אחרים, לרבות שם, מגדר, גיל, סגנון דתי, עיר, טלפון, אנשי קשר, קשר אישי, תמונות, הערות, העדפות, תזכורות, רעיונות לשידוך והיסטוריית הטיפול בהם. אנשים שמופיעים במאגר אינם הופכים למשתמשי האפליקציה ואינם מקבלים הודעה אוטומטית.

אנשי קשר ותמונות

- ייבוא אנשי קשר מציג שמות ומספרים מהמכשיר ומוסיף רק את מי שבחרתם. הרשימה עשויה להישמר זמנית במכשיר לצורך מהירות.
- באנדרואיד נקרא גם הסימון "מועדף" של איש הקשר, כדי להציג את המועדפים בראש רשימת הייבוא. הסימון משמש למיון מקומי בלבד ואינו מועלה.
- בחירת תמונה פותחת את בורר המדיה. Google ML Kit משמש לזיהוי פנים לצורך חיתוך נוח, כולו על המכשיר; התמונה ותוצאת הזיהוי אינן נשלחות ל-ML Kit בענן.
- תוכן ששיתפתם אל האפליקציה מאפליקציה אחרת מועתק זמנית ומתווסף למאגר רק לאחר בחירה מפורשת.

תזכורות וקבצים

התזכורות הן מקומיות ומופעלות במכשיר. ייצוא JSON או Excel, שיתוף כרטיס או פתיחת קובץ גיבוי נעשים ביוזמתכם; עותק שנמסר לאפליקציה אחרת או נשמר מחוץ לאפליקציה נמצא בשליטתכם.

2. למה המידע משמש

המידע משמש להפעלת האפליקציה: ניהול המאגר, יצירת רעיונות, חיפוש וסינון, תזכורות, ייבוא ושיתוף שבחרתם, גיבוי ושחזור, תכונות הקהילה, טיפול בפניות תמיכה ומניעת שימוש לרעה. איננו משתמשים במידע לפרסום, שיווק, פרופיילינג מסחרי או החלטה אוטומטית בעלת תוקף משפטי, ולא נשלח הודעות שיווקיות.

3. אחסון מקומי וגיבוי בענן

Hive והקבצים במכשיר הם מקור המידע הפעיל, ולכן לאחר כניסה האפליקציה יכולה לעבוד ללא רשת. חשבון הוא חובה כדי להפריד בין מאגרים של אנשים שונים באותו מכשיר וכדי לאפשר שחזור.

תחת users/{uid} ב-Cloud Firestore וב-Cloud Storage נשמר גיבוי של אנשים, רעיונות, הערות, היסטוריית פעילות וסטטוסים, הפרופיל ותמונות. הגיבוי רץ בפתיחה, בהשהיה/סגירה ולאחר שינויים, ומיועד לשחזור במכשיר חדש. כללי אבטחה בצד השרת מגבילים אותו לחשבון שיצר אותו; אין באפליקציה מסך מנהל או חיפוש שחושף מאגר של משתמש אחר.

ביציאה מהחשבון מתבצע ניסיון גיבוי אחרון. רק אם הוא הצליח החשבון מנותק וכל המאגר המקומי מנוקה מהמכשיר, כדי שהמשתמש הבא לא יראה אותו. העותק בענן נשאר ויחזור לאחר כניסה חוזרת לאותו חשבון.

4. ייבוא בעזרת Gemini

רק כשאתם מפעילים ייבוא בעזרת AI, הטקסט שחילצתם מקובץ Excel, גיבוי שיחה או כרטיס נשלח ל-Gemini באמצעות Firebase AI Logic ו-Vertex AI בנקודת קצה גלובלית. הטקסט עלול לכלול שמות, גילים, טלפונים ופרטים אחרים שבקובץ. תמונות אינן נשלחות למודל במסלול זה. התוצאה מוצגת לבדיקה ונכתבת למאגר רק לאחר אישור.

השימוש כפוף לתנאי Google Cloud ולתנאים הייעודיים לשירותי Generative AI. Google מצהירה שלא תשתמש בנתוני לקוח לאימון או לכוונון מודלים ללא רשות או הוראה, אך עשויה לעבד או לשמור מידע במידה הנדרשת לאבטחה, מניעת שימוש לרעה, תפעול השירות או caching, בהתאם להגדרות ולתנאים שלה. אם אינכם רוצים להעביר טקסט למודל, אפשר ליצור ולייבא רשומות בדרכים שאינן AI.

4א. הכרטיס האישי וגישה של חברים

מי שנכנס כרווק/ה יכול למלא כרטיס אישי על עצמו ולנהל אותו בעצמו. הכרטיס נשמר ב-Cloud Firestore תחת personalCards/{uid} והתמונות שלו ב-Cloud Storage. הוא כולל את מה שבעל הכרטיס מילא: שם, מגדר, תאריך לידה, סגנון דתי, עיר, אזור, מצב משפחתי, גובה, הכרטיסייה לשליחה, תמונות, "מה אני מחפש/ת" וסטטוס. מספר הטלפון אינו חלק מהכרטיס.

- מי רואה את הכרטיס: רק בעל הכרטיס ושדכנים שהוא אישר. ההרשאה נבדקת בשרת, בכללי האבטחה של Firebase, ולא רק באפליקציה. אישור ניתן לכל הכרטיס, ואפשר להסיר אותו או להסתיר את הכרטיס משדכן מסוים בכל עת — מבחינתו ייראה כאילו אין לך כרטיס. אפשר גם לכבות לגמרי את האפשרות של שדכנים לבקש גישה; גם אז אפשר לתת גישה לחברים ביוזמתך.
- המספר שלך: כדי שחברים יזהו אותך, נשמר "טביעת" גיבוב (hash) של מספר הטלפון שהזנת, יחד עם השם שלך וסימון אם יש לך כרטיס או שאתה משדך. אפשר לחפש מספר אחד בכל פעם, ואי אפשר לעבור על הרשימה. גיבוב של מספר טלפון אינו סוד מוחלט — הוא מסתיר את המספר מקריאה, לא מניסיון מכוון.
- אנשי הקשר של בעל הכרטיס: רק אם בעל הכרטיס מאשר גישה לאנשי הקשר, נשלח לשרת גיבוב של המספרים שבאנשי הקשר — בלי שמות ובלי המספרים עצמם. השרת משתמש בו כדי למצוא אילו חברים משדכים, וכדי לוודא ששדכן שמבקש גישה שמור אצל בעל הכרטיס. הרשימה מוחלפת בכל עדכון וגלויה רק לכללי השרת.
- המאגר של השדכן: כשאתם מחוברים ומשדכים, נשלח לשרת גיבוב של מספרי הטלפון של החברים במאגר שלכם — בלי שמות ובלי המספרים עצמם. השרת משתמש בו רק כדי להודיע לכם כשחבר מהמאגר ממלא לעצמו כרטיס אישי, כדי שתוכלו לבקש ממנו גישה. אף משתמש אחר לא יכול לקרוא אותו; הוא מוחלף בכל עדכון ונמחק עם החשבון.
- אצל השדכן: פרטי הכרטיס ותמונותיו נשמרים גם במכשיר של שדכן מאושר, כדי שיוכל לעבוד איתם ולשתף אותם כמו כל כרטיס. ההערות, הרעיונות והמידע שהשדכן כתב בעצמו — כולל שינויים שעשה בעותק שלו של הכרטיס ובסטטוס — נשארים אצלו בלבד ולעולם אינם מגיעים לבעל הכרטיס או לשדכן אחר. העדכון הוא חד־כיווני: שינויים שבעל הכרטיס עושה מגיעים לשדכנים המאושרים. כשהגישה מוסרת או שהכרטיס נמחק, פרטי הכרטיס והתמונות שהגיעו ממנו מוסרים מהמכשיר של השדכן, והגרסה שהייתה לשדכן לפני כן חוזרת.
- מחיקת הכרטיס: מוחקת את הכרטיס בלבד, לא את החשבון. הכרטיס נשמר מסומן כמחוק כדי שאפשר יהיה לשחזר אותו, והשדכנים מפסיקים לראות אותו מיד. הוא נמחק לגמרי עם מחיקת החשבון.
- התראות: השרת (Cloud Functions) כותב לחשבון התראות על בקשת גישה, אישור או דחייה, כרטיס של חבר, חתונה ויום הולדת עברי, ושולח אותן כהתראת Push דרך Firebase Cloud Messaging. לשם כך נשמר מזהה המכשיר להתראות. על שינויים רגילים בכרטיס לא נשלחות התראות.
- הזמנה: שדכן יכול לשלוח לחבר קישור הזמנה שכולל את מזהה השדכן ושמו. ההזמנה לא נותנת גישה לאיש; בעל הכרטיס מחליט.

5. הקהילה והפרופיל הציבורי

לכל חשבון עשויה להישמר רשומת קהילה הכוללת מוני פעילות לתקופות שונות: נקודות, חברים, רעיונות, זוגות שיצאו ואירוסין. שאר המשתמשים המחוברים קוראים את המונים לצורך סכומי הקהילה והדירוג.

אם בחרתם להופיע בשם, יכולים להופיע גם פרטי הפרופיל שלכם בלבד: שם, תמונת פרופיל, משפט קצר, תשובות שבחרתם לשתף, הטבה לקהילה ומספר WhatsApp שהזנתם מרצונכם. יש להתייחס אליהם כמידע הגלוי לכל משתמש מחובר. אפשר להסתיר את השם והפרופיל, לעצור פרסום לקהילה או למחוק את רשומת הקהילה ממסך "פרטיות והמאגר שלי".

שום שם, טלפון, הערה או תמונה של אדם ממאגר השידוכים אינו נכתב ברשומת הקהילה.

6. הודעות אירוסין וברכות

כאשר רעיון מסומן כחתונה נוצרת הודעת קהילה זמנית הכוללת זמן, מזהה החשבון של השדכן ומזהה רעיון אקראי וחסר משמעות ללא המאגר שלו. היא אינה כוללת שם, תמונה, גיל או פרט אחר של בני הזוג. שמו של השדכן מתווסף רק לאחר הסכמה נפרדת. ההודעה מוצגת עד שבוע ומיועדת למחיקה אוטומטית מ-Firestore לאחר תקופת שמירה של עד 28 יום.

משתמש אחר יכול לשלוח ברכת "מזל טוב". הודעה זו כוללת את מזהי השולח והמקבל, שם השולח אם פורסם, מזהה הרעיון וטקסט הברכה. רק השולח והמקבל רשאים לקרוא אותה; היא נמחקת לאחר שנמסרה ליומן המקומי, ובכל מקרה מיועדת למחיקת TTL לאחר עד 90 יום.

7. טיפים לקהילה

אם שלחתם טיפ לקהילה, נשמרים טקסט הטיפ, השם שבפרופיל, מזהה החשבון וסטטוס הבדיקה. טיפים שאושרו גלויים למשתמשים מחוברים. מנהלי התמיכה בודקים, מאשרים או דוחים אותם. מחיקת החשבון מוחקת את הטיפים שלכם.

8. פניות תמיכה

אם שלחתם תקלה או רעיון, נשמרים הטקסט, סוג הפנייה, השם ומזהה החשבון שלכם, דגם המכשיר, מערכת ההפעלה, גרסת האפליקציה, מועד השליחה ותמונה שצירפתם. תגובות שלכם ושל צוות שדכן נשמרות בשרשור. רק אתם ומנהלי התמיכה המורשים רשאים לקרוא את הפנייה והשרשור.

פניות ושרשורים נשמרים כל עוד הם דרושים לטיפול, לתיעוד תקלה, לאבטחה ולמניעת שימוש לרעה. הם אינם נמחקים אוטומטית עם החשבון, והמדיניות הזאת מוצגת גם באישור המחיקה. אפשר לבקש מחיקה מוקדמת בכתובת giladsh22@gmail.com; בקשה עשויה להידחות או להידחות בזמן אם הדין מחייב שמירה.

9. App Check ואבטחת השירות

Firebase App Check שולח ל-Google או ל-Apple חומר attestation ואסימונים כדי לבדוק שהבקשה מגיעה מהתקנה אמיתית. לפי Firebase, חומר ה-attestation אינו נשמר ב-App Check; אסימונים מוגבלים בזמן, ואסימונים שמופעלת עליהם הגנת replay עשויים להישמר עד 30 יום. אין להשתמש ב-App Check כדי לזהות את תוכן המאגר.

10. אתר המידע

האתר הסטטי ב-Firebase Hosting אינו כולל חשבון, טפסים, עוגיות, פרסומות או כלי אנליטיקה. Firebase Hosting ו-Google עשויים לעבד נתוני חיבור טכניים, כגון כתובת IP ו-user-agent, כדי למסור את הדפים, לאבטח את השירות ולמנוע שימוש לרעה, בהתאם לתנאי Google.

תגיות: התגיות שמוסיפים לחברים הן כלי פנימי — הן נשמרות במאגר שלך ובגיבוי שלך בלבד ואינן חלק מהכרטיס. עבור "השראה מהקהילה" נשלחת לשרת רק רשימת *המילים* הכלליות שבשימוש (בלי שיוך לאף אדם, ובלי תגיות שנראות כשם של מקום, מוסד, יחידה או קבוצה). את הרשימה שלך אינו רואה אף אחד מלבדך; המערכת סופרת כמה שדכנים שונים משתמשים בכל מילה, ומציגה מילה לאחרים רק כשלפחות שלושה משתמשים בה — בלי לחשוף מי. במצב פרטי לא נשלח דבר, והרשימה נמחקת עם החשבון.

11. הרשאות

האפליקציה עשויה לבקש אנשי קשר, תמונות/מדיה, מיקרופון והתראות — רק בעת שימוש בתכונה המתאימה. המיקרופון משמש רק להקלטת הערה קולית על חבר מתוך הפרופיל שלו; הקלטות (כולל הקלטות ששותפו לאפליקציה מווטסאפ) נשמרות במכשיר בלבד, אינן עולות לגיבוי בענן ואינן נשלחות לשום גורם, ונמחקות עם ההערה. בכרטיס האישי, אנשי הקשר נדרשים רק כדי למצוא חברים שמשדכים ולתת או לבקש גישה; שאר האפליקציה עובדת גם בלי ההרשאה. אפשר לבטל הרשאה בהגדרות המכשיר, אך התכונה התלויה בה עלולה לא לעבוד.

12. שירותים חיצוניים והעברות בינלאומיות

האפליקציה משתמשת ב-Firebase Authentication, Cloud Firestore, Cloud Storage, Cloud Functions, Firebase Cloud Messaging, Firebase App Check, Firebase AI Logic/Vertex AI ו-Firebase Hosting של Google; ב-Google Sign-In, Google ML Kit ושירותי החנות; וב-Sign in with Apple במכשירי Apple. לכל ספק מדיניות ותנאים משלו.

המידע עשוי להיות מעובד מחוץ למדינת מגוריכם. Firebase Authentication מופעל ממרכזי נתונים בארצות הברית; שירותים גלובליים ושירותי AI עשויים לעבד מידע במיקומים נוספים. במקום שנדרש אנו מסתמכים על הסכמי עיבוד הנתונים ומנגנוני ההעברה של Google ועל מנגנונים חוקיים אחרים.

13. שמירה ומחיקה

- נתונים מקומיים נשמרים עד שמוחקים אותם, מוחקים את החשבון או מסירים את האפליקציה.
- הגיבוי נשמר עד שמוחקים אותו במסך הפרטיות או מוחקים את החשבון. הסרת האפליקציה לבדה אינה מוחקת גיבוי.
- נתוני קהילה ניתנים למחיקה מיידית במסך הפרטיות.
- הודעות אירוסין וברכות נשמרות לזמנים המפורטים בסעיף 6.
- טיפים שלכם נמחקים עם החשבון.
- כרטיס אישי שנמחק נשמר מסומן כמחוק עד שחזורו או עד מחיקת החשבון. גיבוב אנשי הקשר וגיבוב המאגר מוחלפים בכל עדכון ונמחקים עם החשבון. התראות בחשבון נשמרות עד שמוחקים אותן או את החשבון.
- פניות תמיכה נשמרות לפי סעיף 8.
- Firebase Authentication עשוי לשמור יומני IP במשך כמה שבועות. לאחר מחיקת משתמש, Firebase מציינת שמידע Authentication מוסר ממערכות פעילות וגיבוי בתוך עד 180 יום.

14. מחיקת החשבון

אפשר להתחיל ולסיים מחיקת חשבון בתוך האפליקציה: הפרופיל שלי → בתחתית העמוד → מחיקת החשבון והנתונים. האפליקציה מבקשת אימות מחדש באמצעות Apple, Google או הסיסמה, לפי החשבון. בחשבון Apple מתקבל קוד הרשאה חדש ונשלח ל-Firebase כדי לבטל את אסימוני Apple לפני מחיקת המשתמש.

המחיקה מסירה את חשבון Firebase, הגיבוי והתמונות בענן, הכרטיס האישי ותמונותיו, אישורי הגישה, גיבוב המספר, אנשי הקשר והמאגר, ההתראות, נתוני הקהילה והתמונה הציבורית, פרסומי האירוסין, הברכות הממתינות והטיפים, ולאחר מכן מנקה את המאגר המקומי. היא אינה הפיכה. פניות תמיכה נשמרות לפי סעיף 8, וקבצים שייצאתם או מידע ששיתפתם מחוץ לאפליקציה אינם בשליטתנו.

אם אין עוד גישה לאפליקציה, אפשר לבקש מחיקה ב-giladsh22@gmail.com. נאמת בעלות לפני מחיקה.

15. זכויות ובסיסים משפטיים

בהתאם לדין החל, עיבוד הדרוש להפעלת החשבון והאפליקציה מבוסס על ביצוע ההתקשרות; הרשאות, AI ושיתוף מידע מרצון מבוססים על הסכמה; אבטחה, תמיכה ותפעול הקהילה עשויים להתבסס על אינטרס לגיטימי. עשויות לעמוד לכם זכויות עיון, תיקון, מחיקה, הגבלה, התנגדות, ניידות וחזרה מהסכמה, וכן זכות להגיש תלונה לרשות המוסמכת. איננו מוכרים או "משתפים" מידע לצורכי פרסום התנהגותי לפי CCPA/CPRA.

אתם אחראים למידע על אנשים אחרים שהכנסתם למאגר ולבסיס החוקי לשמירתו ולשיתופו. השתמשו באפליקציה כפי שהייתם רוצים שישתמשו במידע עליכם.

16. ילדים

האפליקציה אינה מיועדת לילדים מתחת לגיל 16, או לגיל גבוה יותר שנדרש בדין המקומי, ואיננו אוספים ביודעין מידע מילדים.

17. אבטחה

אנו משתמשים במנגנוני האבטחה של מערכת ההפעלה, Firebase Security Rules, הפרדה לפי uid, App Check והעברה מוצפנת. עם זאת, אין מערכת בטוחה לחלוטין. אבטחת המכשיר, חשבון ספק ההתחברות וקבצים שייצאתם היא גם באחריותכם.

18. שינויים ויצירת קשר

שינוי מהותי יקבל תאריך עדכון חדש ויוצג לפי הצורך. לשאלות, למימוש זכויות או לבקשת מחיקה: גלעד שטרוזמן — giladsh22@gmail.com.

הנוסח העברי הוא הנוסח הקובע במקרה של אי-התאמה לתרגום האנגלי.
''';

  static const String english = '''
Privacy Policy — Shadchan

Last updated: September 25, 2026

This policy applies to the Shadchan application and its information website. The Application is developed and operated by Gilad Shtruzman ("we"), the controller of the processing described here. Privacy contact: giladsh22@gmail.com.

In brief

The Application is local-first: the active database lives on the device and continues to work offline. An account is nevertheless required, and a cloud backup is kept automatically in Firebase under that account's identifier. The Application contains no advertising, analytics SDK, crash-reporting SDK, cookies or behavioural tracking, and we do not sell personal information.

1. Information processed

Your account

You can sign in with Google, with Apple on supported Apple devices, or with an email address and password. Firebase Authentication processes the account identifier, sign-in provider, email address and basic profile details supplied by the provider. Passwords for email accounts are handled by Firebase and are not visible to us. For security and abuse prevention, Firebase may also process IP addresses, user-agent strings and sign-in logs. Before sign-in or after sign-out, the Application may create a temporary technical anonymous Firebase identifier; it receives no backup and cannot pass the sign-in gate.

Matchmaking database

You may enter information about yourself and other people, including names, gender, age, religious style, city, telephone number, contact people, how you know them, photographs, private notes, preferences, reminders, match ideas and their handling history. People in your database do not become users and are not automatically notified.

Contacts and photographs

- Contact import displays names and phone numbers on the device and adds only the contacts you select. The candidate list may be cached locally for speed.
- On Android the contact's "favourite" flag is also read, so favourites appear at the top of the import list. It is used only for local sorting and is never uploaded.
- Selecting a photograph opens the system media picker. Google ML Kit face detection is used entirely on-device to help crop the image; neither the image nor face-detection output is sent to ML Kit in the cloud.
- Content shared into the Application from another app is copied temporarily and added to the database only after an explicit choice.

Reminders and files

Reminders are local notifications scheduled on the device. Exporting JSON or Excel, sharing a card, or opening a backup file happens at your direction. A copy delivered to another app or stored outside Shadchan is under your control.

2. Purposes

Information is used to operate the Application: database management, match ideas, search and filtering, reminders, imports and sharing you request, backup and restore, community features, support, security and abuse prevention. We do not use it for advertising, marketing, commercial profiling or automated decisions with legal effect, and we do not send marketing communications.

3. Local storage and cloud backup

Hive and local files are the active source of truth, so the Application can work offline after sign-in. An account is required to separate different users' databases on one device and to make restoration possible.

A backup under users/{uid} in Cloud Firestore and Cloud Storage includes people, ideas, notes, activity and status history, the profile and photographs. It runs on app open, pause/close and after changes, and is used to restore the database on a new device. Server-side rules restrict it to the account that created it; the Application has no administrator screen or cross-account database search.

Signing out first attempts a final backup. Only after it succeeds does the Application disconnect the account and clear the local database, so the next user cannot see it. The cloud copy remains and returns when the same account signs in again.

4. Gemini-assisted import

Only when you start an AI-assisted import, text extracted from an Excel file, chat backup or profile card is sent to Gemini through Firebase AI Logic and Vertex AI at a global endpoint. It may contain names, ages, telephone numbers and other content in the selected file. Photographs are not sent to the model in this flow. Parsed results are shown for review and written only after acceptance.

Use is governed by the Google Cloud and Generative AI service terms. Google states that it will not use customer data to train or fine-tune AI/ML models without permission or instruction, but may process or retain data as needed for security, abuse monitoring, operation or caching under its settings and terms. If you do not want to send text to a model, use the manual and non-AI import paths.

4A. The personal card and access by friends

Someone who signs in as a single person may write a personal card about themselves and manage it themselves. The card is stored in Cloud Firestore under personalCards/{uid} and its photographs in Cloud Storage. It contains what the owner filled in: name, gender, date of birth, religious style, city, region, marital status, height, the card text, photographs, "what I am looking for" and a status. The phone number is not part of the card.

- Who sees the card: only its owner and matchmakers the owner approved. Access is checked on the server, in Firebase Security Rules, not only in the Application. Access covers the whole card and can be withdrawn, or the card hidden from a particular matchmaker, at any time — to them it looks as if there is no card. Access requests can also be switched off altogether; the owner can still give friends access on their own initiative.
- Your number: so that friends can recognise you, a hash of the phone number you entered is stored with your name and whether you have a card or match. Numbers can be looked up one at a time; the list cannot be read out. A hash of a phone number is not a strong secret — it hides the number from reading, not from a determined attempt.
- The owner's contacts: only if the owner grants contacts access, hashes of the numbers in their contacts are sent to the server — no names and no numbers. The server uses them to find which friends match, and to verify that a matchmaker requesting access is saved in the owner's contacts. The list is replaced on every update and is visible only to the server's rules.
- A matchmaker's database: while you are signed in as a matchmaker, hashes of the phone numbers of the friends in your database are sent to the server — no names and no numbers. The server uses them only to tell you when a friend in your database writes a personal card of their own, so that you can ask them for access. No other user can read them; they are replaced on every update and erased with the account.
- On the matchmaker's device: an approved matchmaker's device keeps the card's details and photographs so the matchmaker can work with and share them like any card. Notes, ideas and information the matchmaker wrote themselves — including changes they make to their own copy of the card and its status — stay with that matchmaker only and never reach the owner or another matchmaker. Updates flow one way: changes the owner makes reach the approved matchmakers. When access is withdrawn or the card is deleted, the details and photographs received from it are removed from the matchmaker's device and the matchmaker's earlier version is restored.
- Deleting the card: removes the card only, not the account. The card is kept flagged as deleted so it can be restored, and matchmakers stop seeing it at once. It is erased completely with account deletion.
- Notifications: server functions (Cloud Functions) write notices to the account about access requests, approvals or declines, a friend's card, a wedding and a Hebrew birthday, and send them as push notifications through Firebase Cloud Messaging. A device notification token is stored for this. Ordinary changes to a card send no notification.
- Invitations: a matchmaker may send a friend an invitation link containing the matchmaker's identifier and name. An invitation grants access to nobody; the card owner decides.

5. Community and public profile

An account may have a community document with period activity counters: points, friends, ideas, couples dating and engagements. Other signed-in users read those counters to produce community totals and the leaderboard.

If you choose to appear by name, the following details about you only may also be visible: profile name, profile picture, short introduction, answers you chose to share, a community benefit and a WhatsApp number you entered voluntarily. Treat them as visible to every signed-in user. You can hide the named profile, stop community publishing or erase the community document from "Privacy and my database".

No name, phone number, note or photograph of a person in your matchmaking database is written to the community member document.

6. Engagement announcements and congratulations

When an idea is marked as a wedding, a temporary community announcement contains a timestamp, the matchmaker's account identifier and a random idea identifier meaningless without their local database. It contains no name, photograph, age or other detail about the couple. The matchmaker's own name is added only after separate consent. It is displayed for up to one week and intended for Firestore TTL deletion after a retention period of no more than 28 days.

Another user may send a "Mazal tov" message. It contains sender and recipient identifiers, the sender's name if published, the idea identifier and the message text. Only sender and recipient may read it. It is deleted after delivery to the local journal and is intended for TTL deletion after no more than 90 days.

7. Community tips

If you submit a tip, its text, your profile name, account identifier and review status are stored. Approved tips are visible to signed-in users. Support administrators review, approve or reject them. Your tips are deleted when your account is deleted.

8. Support requests

If you send a problem or idea, we store the text, request type, your name and account identifier, device model, operating system, app version, submission time and any image you attach. Replies from you and the Shadchan team are kept in a thread. Only you and authorised support administrators can read the request and thread.

Support correspondence is retained while needed to handle the request, document a defect, secure the service and prevent abuse. It is not deleted automatically with the account; this is also stated in the deletion confirmation. You may request earlier deletion at giladsh22@gmail.com, subject to any legal retention requirement.

9. App Check and service security

Firebase App Check sends attestation material and tokens to Google or Apple to verify genuine installations. Firebase states that App Check does not retain attestation material; tokens are time-limited, and tokens used with replay protection may be kept for up to 30 days. App Check is not used to identify database content.

10. Information website

The static website on Firebase Hosting has no accounts, forms, cookies, advertising or analytics. Firebase Hosting and Google may process technical connection information, such as IP address and user-agent, to deliver pages, secure the service and prevent abuse under Google's terms.

Tags: tags you put on friends are an internal tool — they stay in your database and your own backup and are not part of any card. For "community inspiration" only the list of general tag *words* in use is sent (not linked to any person, and excluding tags that look like the name of a place, institution, unit or group). Nobody but you can read your list; the service counts how many different matchmakers use each word and shows a word to others only once at least three use it — without revealing who. Nothing is sent in private mode, and the list is deleted with the account.

11. Permissions

The Application may request contacts, photos/media, the microphone and notifications only when the related feature is used. The microphone is used only to record a voice note about a friend from their profile; recordings (including ones shared into the Application from WhatsApp) stay on the device, are not included in the cloud backup, are not sent anywhere, and are deleted with the note. For the personal card, contacts are needed only to find friends who match and to give or request access; the rest of the Application works without that permission. You may revoke a permission in device settings, although the dependent feature may stop working.

12. Providers and international transfers

The Application uses Google's Firebase Authentication, Cloud Firestore, Cloud Storage, Cloud Functions, Firebase Cloud Messaging, Firebase App Check, Firebase AI Logic/Vertex AI and Firebase Hosting; Google Sign-In, Google ML Kit and store services; and Sign in with Apple on Apple devices. Each provider has its own terms and privacy policy.

Information may be processed outside your country. Firebase Authentication operates from US data centres; global and AI services may process data in other locations. Where required, we rely on Google data-processing agreements and transfer mechanisms and other lawful safeguards.

13. Retention and erasure

- Local data remains until you delete it, delete the account or uninstall the Application.
- Backup remains until erased from the privacy screen or through account deletion. Uninstalling alone does not erase it.
- Community data can be erased immediately from the privacy screen.
- Engagement records and congratulations follow section 6.
- Your tips are erased with the account.
- A deleted personal card is kept flagged as deleted until restored or until account deletion. Contact and database hashes are replaced on every update and erased with the account. Notices in the account remain until you remove them or the account.
- Support correspondence follows section 8.
- Firebase Authentication may keep logged IP addresses for a few weeks. Firebase states that after user deletion, Authentication data is removed from live and backup systems within 180 days.

14. Account deletion

Account deletion can be completed inside the Application: My profile → bottom of the page → Delete account and data. The Application asks you to reauthenticate with Apple, Google or your password. For an Apple-linked account, it obtains a fresh authorization code and sends it to Firebase to revoke Apple tokens before deleting the user.

Deletion removes the Firebase user, cloud backup and photographs, the personal card and its photographs, access grants, the phone, contact and database hashes, notices, community data and public avatar, engagement announcements, pending congratulations and tips, then clears the local database. It cannot be undone. Support correspondence follows section 8, and exported files or information shared outside the Application remain outside our control.

If you no longer have access to the Application, request deletion at giladsh22@gmail.com. We will verify ownership first.

15. Rights and legal bases

Depending on applicable law, processing necessary to run the account and Application is based on performance of the service; permissions, AI and voluntary publication rely on consent; and security, support and community operations may rely on legitimate interests. You may have rights of access, correction, erasure, restriction, objection, portability and withdrawal of consent, and the right to complain to a supervisory authority. We do not sell or "share" personal information for cross-context behavioural advertising under the CCPA/CPRA.

You are responsible for information about other people that you enter, including having a lawful basis to keep and share it. Use the Application as you would want someone to use information about you.

16. Children

The Application is not intended for children under 16, or a higher age required by local law, and we do not knowingly collect information from children.

17. Security

We use operating-system protections, Firebase Security Rules, uid separation, App Check and encrypted transport. No system is completely secure. You are also responsible for securing the device, sign-in provider account and exported files.

18. Changes and contact

A material change will carry a new update date and be presented where required. For questions, rights requests or deletion requests: Gilad Shtruzman — giladsh22@gmail.com.

If the English translation differs from the Hebrew policy, the Hebrew policy prevails.
''';
}
