"""The page an invitation link opens: https://shadchan-gilad.web.app/join.

It is the one page on the site a person reaches from a friend, on a phone, on
the way into the app — so it wears the app itself rather than the documents'
shell: the cream paper, the card with the copper rule along its foot, the
stone-blue ink, the app's own font and buttons. Keep the colours in step with
`lib/utils/app_colors.dart`.

The font files in `site/fonts/` are the app's Google Sans (OFL), cut down to
Latin + Hebrew and saved as WOFF (~33KB each) with fontTools — the TTFs in
`assets/fonts/` are almost 2MB apiece. `site/icon.png` is
`assets/icon/app_icon.png` at 192px. Neither is regenerated by the build.
"""

JOIN_CSS = """
@font-face { font-family: 'Google Sans'; font-weight: 400;
  src: url('fonts/GoogleSans-Regular.woff') format('woff'); font-display: swap; }
@font-face { font-family: 'Google Sans'; font-weight: 700;
  src: url('fonts/GoogleSans-Bold.woff') format('woff'); font-display: swap; }
:root {
  --paper: #F7F0E4; --card: #FFFDF8; --ink: #3F5A66; --body: #211D17;
  --muted: #5E5C58; --copper: #C1845B; --copper-ink: #211D17;
  --line: #E2D7C8; --wash: #EFE4D4; --blue-wash: #D7E4EA;
  --shadow: 0 6px 22px rgba(33, 29, 23, 0.10), 0 1px 3px rgba(33, 29, 23, 0.06);
  color-scheme: light dark;
}
@media (prefers-color-scheme: dark) {
  :root {
    --paper: #1D262B; --card: #263239; --ink: #A9C3CE; --body: #EDE6DA;
    --muted: #B5ADA1; --line: #3A4850; --wash: #2F3B42; --blue-wash: #2F3E46;
    --shadow: 0 6px 22px rgba(0, 0, 0, 0.35);
  }
}
* { box-sizing: border-box; }
html, body { margin: 0; }
body {
  background: var(--paper); color: var(--body);
  font-family: 'Google Sans', 'Segoe UI', Arial, sans-serif;
  line-height: 1.55; -webkit-font-smoothing: antialiased;
  min-height: 100vh; display: flex; flex-direction: column; align-items: center;
  padding: 32px 16px 24px;
}
.brand { display: flex; flex-direction: column; align-items: center; gap: 10px;
  margin-bottom: 22px; }
.brand img { width: 76px; height: 76px; border-radius: 20px; box-shadow: var(--shadow); }
.brand .word { font-weight: 700; font-size: 26px; color: var(--ink); }
.card {
  width: 100%; max-width: 440px; background: var(--card); border-radius: 20px;
  box-shadow: var(--shadow); padding: 26px 22px 26px; position: relative;
  overflow: hidden;
}
.card::after {
  content: ''; position: absolute; inset-inline: 22px; bottom: 0; height: 3px;
  border-radius: 3px 3px 0 0; background: var(--copper);
}
.eyebrow { display: inline-block; font-size: 13px; font-weight: 700; color: var(--ink);
  background: var(--blue-wash); border-radius: 999px; padding: 4px 12px; margin: 0 0 12px; }
.eyebrow:empty { display: none; }
h1 { margin: 0 0 8px; font-size: 26px; line-height: 1.25; color: var(--ink); font-weight: 700; }
.lead { margin: 0 0 12px; font-size: 16px; color: var(--muted); }
.lead + .lead { margin-bottom: 20px; }
.lead strong { color: var(--ink); }
.button {
  display: flex; align-items: center; justify-content: center; gap: 8px;
  width: 100%; min-height: 50px; padding: 12px 18px; border-radius: 14px;
  font: inherit; font-weight: 700; font-size: 16px; text-decoration: none;
  cursor: pointer; transition: transform .08s ease;
}
.button:active { transform: translateY(1px); }
.primary { background: var(--copper); color: var(--copper-ink);
  box-shadow: 0 3px 10px rgba(193, 132, 91, 0.35); }
.secondary { background: transparent; color: var(--ink); border: 1px solid var(--line);
  margin-top: 10px; }
.points { list-style: none; margin: 22px 0 0; padding: 0; display: grid; gap: 12px; }
.points li { display: flex; gap: 12px; align-items: flex-start; }
.dot { flex: 0 0 34px; height: 34px; border-radius: 11px; background: var(--wash);
  color: var(--copper); display: flex; align-items: center; justify-content: center; }
.dot svg { width: 18px; height: 18px; }
.points strong { display: block; color: var(--ink); font-size: 15px; }
.points span { display: block; color: var(--muted); font-size: 14px; }
.note { max-width: 440px; margin: 16px 4px 0; font-size: 13px; color: var(--muted);
  text-align: center; }
footer { margin-top: auto; padding-top: 28px; font-size: 13px; }
footer a { color: var(--muted); }
"""

_HEART = (
    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" '
    'stroke-linecap="round" stroke-linejoin="round"><path d="M12 20s-7-4.4-7-10a4 4 0 0 1 '
    '7-2.6A4 4 0 0 1 19 10c0 5.6-7 10-7 10z"/></svg>'
)
_LOCK = (
    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" '
    'stroke-linecap="round" stroke-linejoin="round"><rect x="5" y="11" width="14" '
    'height="9" rx="2.5"/><path d="M8 11V8a4 4 0 0 1 8 0v3"/></svg>'
)
_SYNC = (
    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" '
    'stroke-linecap="round" stroke-linejoin="round"><path d="M20 12a8 8 0 0 1-13.7 '
    '5.7M4 12a8 8 0 0 1 13.7-5.7"/><path d="M18 3v4h-4M6 21v-4h4"/></svg>'
)

_TEMPLATE = """<!doctype html>
<html lang="he" dir="rtl">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<meta name="theme-color" content="#F7F0E4">
<title>הוזמנת לשדכן</title>
<meta name="description" content="שדכן — יומן אישי לניהול שידוכים בין חברים, עם אזור אישי לניהול כרטיס השידוכים שלך.">
<link rel="icon" href="icon.png">
<link rel="apple-touch-icon" href="icon.png">
<link rel="preload" href="fonts/GoogleSans-Bold.woff" as="font" type="font/woff" crossorigin>
<style>__CSS__</style>
</head>
<body>
  <div class="brand">
    <img src="icon.png" alt="" width="76" height="76">
    <span class="word">שדכן</span>
  </div>
  <main class="card">
    <p class="eyebrow" id="from"></p>
    <h1>הוזמנת לשדכן</h1>
    <p class="lead"><strong>״שדכן״ היא יומן אישי לניהול שידוכים בין חברים.</strong> מי שמשדך יכול לנהל בה חברים, רעיונות והצעות – ולך יש בה אזור אישי משלך לניהול כרטיס השידוכים שלך.</p>
    <p class="lead">באזור האישי אפשר לעדכן פרטים ותמונות ולבחור למי מהחברים שמשדכים לתת גישה.</p>
    <a class="button primary" id="open" href="#">פתיחה באפליקציה</a>
    <a class="button secondary" id="download" href="__LANDING__">הורדת האפליקציה</a>
    <ul class="points">
      <li><span class="dot">__HEART__</span><div><strong>הכרטיס שלך, בידיים שלך</strong><span>הפרטים והתמונות שלך מתעדכנים מתי שתרצה.</span></div></li>
      <li><span class="dot">__LOCK__</span><div><strong>אתה בוחר מי רואה</strong><span>אף אחד לא מקבל גישה לכרטיס בלי אישור שלך.</span></div></li>
      <li><span class="dot">__SYNC__</span><div><strong>עדכון אחד – והכרטיס נשאר מעודכן</strong><span>מי שכבר קיבל גישה רואה את העדכונים שלך.</span></div></li>
    </ul>
  </main>
  <p class="note" id="note">עצם ההזמנה לא נותנת לאף אחד גישה לכרטיס שלך. אתה מחליט למי לתת גישה.</p>
  <footer><a href="privacy.html">מדיניות פרטיות</a></footer>
<script>
(function () {
  var q = new URLSearchParams(location.search);
  var from = q.get('from') || '';
  var name = (q.get('name') || '').slice(0, 40);
  if (!/^[A-Za-z0-9_-]{6,128}$/.test(from)) { from = ''; }
  var pair = 'from=' + encodeURIComponent(from) + '&name=' + encodeURIComponent(name);
  if (name) {
    document.getElementById('from').textContent = 'הזמנה מ' + name;
  }
  document.getElementById('open').href = 'shadchan-invite://join?' + pair;
  // One download button. The shared landing link sends every phone to its own
  // store; on Android the button goes to Google Play directly instead, because
  // only that link carries the invitation into the app after the install.
  if (/Android/i.test(navigator.userAgent)) {
    document.getElementById('download').href =
      '__PLAY__&referrer=' + encodeURIComponent(pair);
  }
  if (/iPhone|iPad|iPod/.test(navigator.userAgent)) {
    // An iPhone cannot hand the invitation to a freshly installed app.
    document.getElementById('note').textContent =
      'באייפון: אחרי ההתקנה חוזרים לקישור הזה ולוחצים שוב על ״פתיחה באפליקציה״. '
      + 'עצם ההזמנה לא נותנת לאף אחד גישה לכרטיס שלך. אתה מחליט למי לתת גישה.';
  }
})();
</script>
</body>
</html>
"""


def join_page(*, play_url: str, landing_url: str) -> str:
    return (
        _TEMPLATE.replace("__CSS__", JOIN_CSS)
        .replace("__PLAY__", play_url)
        .replace("__LANDING__", landing_url)
        .replace("__HEART__", _HEART)
        .replace("__LOCK__", _LOCK)
        .replace("__SYNC__", _SYNC)
    )
